[workspace]
authors = ["meganfrisella <meganfrisella@gmail.com>"]
channels = ["conda-forge"]
name = "soil-moisture-au26"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.7,<3.15"
matplotlib = ">=3.11.2,<4"
numpy = ">=2.5.3,<3"
pandas = ">=3.0.6,<4"
